# MKDEVENV 0.1.0 (x-release-please-version)
FROM docker.io/golang:latest

ARG USERNAME=mkdevenv

LABEL mkdevenv.name="go-community" \
      mkdevenv.summary="Image with general tools for developing Go-related projects" \
      mkdevenv.usage="For more information, see <https://github.com/ttybitnik/mkdevenv>"

COPY .mkdevenv/*.txt /tmp/

RUN apt-get update && xargs -n 1 apt-get install -y < /tmp/apt.txt \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && adduser $USERNAME \
    && chown $USERNAME:$USERNAME /tmp/*.txt \
    && ln -s /usr/local/go/bin/* /usr/local/bin/

WORKDIR /home/$USERNAME/workspace

COPY go.mod go.sum ./
RUN chown $USERNAME:$USERNAME ./go.mod ./go.sum

USER $USERNAME

ENV GOPATH=/home/$USERNAME/go \
    GOBIN="/home/$USERNAME/.local/bin" \
    NPM_CONFIG_PREFIX="/home/$USERNAME/.local"

RUN xargs -n 1 go install < /tmp/go.txt
RUN xargs -n 1 npm install -g < /tmp/npm.txt && npm cache clean --force
RUN go mod download && go mod verify

CMD ["/bin/bash", "-l"]