# MKDEVENV 0.1.0 (x-release-please-version)
FROM docker.io/fedora:latest

ARG USERNAME=mkdevenv

LABEL mkdevenv.name="lua-fedora" \
      mkdevenv.summary="Image with general tools for developing Lua-related projects" \
      mkdevenv.usage="For more information, see <https://github.com/ttybitnik/mkdevenv>"

COPY .mkdevenv/*.txt /tmp/

RUN dnf update -y && xargs -n 1 dnf install -y < /tmp/dnf.txt && dnf clean all \
    && adduser $USERNAME \
    && chown $USERNAME:$USERNAME /tmp/*.txt

WORKDIR /home/$USERNAME/workspace

USER $USERNAME

ADD https://github.com/LuaLS/lua-language-server/releases/latest/download/lua-language-server-3.10.6-linux-x64.tar.gz \
    /home/$USERNAME/.local/bin

CMD ["/bin/bash", "-l"]
