# MKDEV 0.5.0 (x-release-please-version)
FROM docker.io/fedora:latest

ARG USERNAME=mkdev

LABEL mkdev.name="go-fedora" \
      mkdev.summary="Boilerplate with general tools for developing Go-related projects" \
      mkdev.usage="For more information, see <https://github.com/ttybitnik/mkdev>"

COPY .mkdev/*.txt /tmp/

RUN dnf update -y && xargs -n 1 dnf install -y < /tmp/dnf.txt && dnf clean all \
    && adduser $USERNAME \
    && chown $USERNAME:$USERNAME /tmp/*.txt

WORKDIR /home/$USERNAME/workspace

COPY go.mod go.sum ./
RUN chown $USERNAME:$USERNAME ./go.mod ./go.sum

USER $USERNAME

ENV GOPATH=/home/$USERNAME/go \
    GOBIN="/home/$USERNAME/.local/bin"

RUN xargs -n 1 go install < /tmp/go.txt
RUN go mod download && go mod verify

CMD ["/bin/bash", "-l"]
